apiVersion: k8s.starter.org/v1alpha1
kind: KubernetesCluster
metadata:
  name: fromgit
  namespace: app-clusters
spec:
  id: platform-ref-aws
  parameters:
    nodes:
      count: 1
      size: small
