apiVersion: infrastructure.example.org/v1alpha1
kind: VirtualMachine
metadata:
  name: my-vm-from-app
  namespace: default
spec:
  id: my-vm-from-app
  parameters:
    location: West US
    operatingSystem: Linux (Ubuntu)
    vmSize: 1 vCPU, 1 GB
